# pvc-debug-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
  namespace: jenkins-agents
spec:
  containers:
  - name: debug
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /mnt/results
      name: results
  volumes:
  - name: results
    persistentVolumeClaim:
      claimName: test-results-pvc
  restartPolicy: Never
